# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/23-cloud-base"
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  config.hostmanager.enabled = true
  
  # We setup three nodes to be gluster hosts, and one gluster client to mount the volume
  (1..3).each do |i|
    config.vm.define vm_name = "gluster-server-#{i}" do |config|
      #config.cache.scope = :box
      config.vm.hostname = vm_name
      ip = "172.21.12.#{i+10}"
      config.vm.network :private_network, :libvirt__network_name => "storage", :ip => ip
      config.vm.provision :shell, :inline => "dnf install -yq glusterfs glusterfs-fuse glusterfs-server", :privileged => true
      config.vm.provision :shell, :inline => "systemctl enable glusterd.service", :privileged => true
      config.vm.provision :shell, :inline => "systemctl start glusterd.service", :privileged => true
    end #host info
  end #each loop
#  config.vm.define vm_name = "gluster-client" do |config|
#    #config.cache.scope = :box
#    config.vm.hostname = vm_name
#    ip = "172.21.12.10"
#    config.vm.network :private_network, ip: ip
#    config.vm.provision "shell" do |sh|
#    sh.privileged = true
#      sh.inline = "dnf install -yq glusterfs glusterfs-fuse"
#    end
#  end
end #Vagrantfile
